### ISSUE TITLE
Error after compilation

### ISSUE THREAD

**Issue by yegya** [devinrhode2/tweet-bar#5]
Now I'm getting an issue.
Ive installed using npm package manager and I am using grunt to run it.
Downloaded jar file, pasted it into a build folder inside node_modules/grunt-closure-compiler and run
Now the issue is this, java error.

Warning: Command failed: Exception in thread "main" java.lang.UnsupportedClassVersionError: com/google/javascript/jscomp/CommandLineRunner : Unsupported major.minor version 51.0
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
Use --force to continue.

Looks like version error. What should I do now? Using npm install grunt-closure-compiler doesnt download build/compiler.jar file. Ive manually downloaded jar file and used, but still problem.
I've given path like this: closurePath: 'node_modules/grunt-closure-compiler',
Any solution for me. 
I am in a mac machine.

**Comment by yegya** [comment]
Solved. 
Sorry, the jar file I was using was the latest version which caused problem. Don't know the exact issue, may be the developer of jar file can handle that. For now, I've used the old version of jar file from the link you mentioned, and it solved the issue. :)
